input {
  http_poller {
    urls => {

      jolokia_heap => {
        method => post
        url => "http://host.docker.internal:8161/console/jolokia/"
        headers => {
          "Content-Type" => "application/json"
          "Authorization" => "Basic YWRtaW46YWRtaW4="
        }
        body => '{
          "type": "read",
          "mbean": "java.lang:type=Memory",
          "attribute": "HeapMemoryUsage"
        }'
      }

      jolokia_artemis_queue => {
        method => post
        url => "http://host.docker.internal:8161/console/jolokia/"
        headers => {
          "Content-Type" => "application/json"
          "Authorization" => "Basic YWRtaW46YWRtaW4="
        }
        body => '{
          "type": "read",
          "mbean": "org.apache.activemq.artemis:address=\"test\",broker=\"0.0.0.0\",component=addresses,queue=\"test\",routing-type=\"anycast\",subcomponent=queues"
        }'
      }
    }

    schedule => { every => "10s" }
    codec => "json"
  }
}

filter {
  mutate {
    add_field => {
      "source" => "jolokia_artemis"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "artemis-jolokia-metrics"
  }

  stdout { codec => rubydebug }
}
